#
# Generated by zgen.
# This file will be overwritten the next time you run zgen save
#
source "~/.zsh/plugins/zsh-users/zsh-syntax-highlighting-master//zsh-syntax-highlighting.plugin.zsh"
source "~/.zsh/plugins/sharat87/zsh-vim-mode-master//zsh-vim-mode.plugin.zsh"
source "~/.zsh/plugins/dotphiles/dotzsh-master//init.zsh"
source "~/.zsh/plugins/robbyrussell/oh-my-zsh-master/plugins/git/git.plugin.zsh"
source "~/.zsh/plugins/robbyrussell/oh-my-zsh-master/plugins/sudo/sudo.plugin.zsh"
source "~/.zsh/plugins/robbyrussell/oh-my-zsh-master/plugins/command-not-found/command-not-found.plugin.zsh"
source "~/.zsh/plugins/srijanshetty/zsh-pandoc-completion-master//zsh-pandoc-completion.plugin.zsh"
source "~/.zsh/plugins/ehamberg/zsh-cabal-completion-master//cabal.plugin.zsh"

#
# Add our plugins and completions to fpath
#
fpath=(~/.zsh/plugins/zsh-users/zsh-syntax-highlighting-master ~/.zsh/plugins/sharat87/zsh-vim-mode-master ~/.zsh/plugins/dotphiles/dotzsh-master ~/.zsh/plugins/robbyrussell/oh-my-zsh-master/plugins/git ~/.zsh/plugins/robbyrussell/oh-my-zsh-master/plugins/sudo ~/.zsh/plugins/robbyrussell/oh-my-zsh-master/plugins/command-not-found ~/.zsh/plugins/zsh-users/zsh-completions-master/src ~/.zsh/plugins/srijanshetty/zsh-pandoc-completion-master ~/.zsh/plugins/ehamberg/zsh-cabal-completion-master ${fpath})
